class Colormap: ...
class Normalize:
    def __init__(self, vmin: float = ..., vmax: float = ..., clip: bool | None = ...) -> None: ...
    def __call__(self, value: list[float] | tuple[float, ...], clip: bool | None = ...) -> list[float] | tuple[float, ...]: ...
    @property
    def vmax(self)-> float: ...