class Affine2DBase(AffineBase): ...
class AffineBase(Transform): ...
class BboxBase(TransformNode): ...
class BboxTransformTo(Affine2DBase):
    def __init__(self, boxout: TransformedBbox) -> None: ...
class Transform(TransformNode): ...
class TransformedBbox(BboxBase): ...
class TransformNode: ...